spring.application.name=email

# Remote MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mails?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
#server.forward-headers-strategy=framework
#app.server-url=https://jobreader.appts.in


# ClickUp
clickup.base-url=https://api.clickup.com/api/v2
clickup.token=pk_100952634_GVMO5B6CF41N3YWFDD75NX31XQJV4FK8
clickup.list-id=901613522676
